import { type Finding, type Severity, type ReviewCategory, makeFinding } from "./finding"
import { type ChangedFile, classifyDbtFile } from "./diff-filter"
import { type Rubric, clampSeverity, exclusionReason } from "./rubric"
import { GENERATED } from "./rule-generators"
import path from "node:path"

/**
 * Declarative rule catalog for dbt/SQL PR review.
 *
 * Each rule is a self-contained, self-verifying scenario: a match pattern over
 * the change (added/removed lines or the new SQL) PLUS a positive `example`
 * (which MUST fire) and a `counter` (which must NOT). The catalog is therefore
 * both the detector set and its test corpus — adding a real-world use-case is a
 * single data entry, which is how this scales to hundreds of checks while
 * staying high-precision.
 *
 * These complement the programmatic detectors in dbt-patterns.ts (which need
 * cross-line logic). Rules here are line/SQL-pattern based.
 *
 * Sources: SQLFluff rule set, dbt best-practice guides, BigQuery/Snowflake/
 * Redshift/Databricks anti-pattern docs, r/dataengineering, dbt-core issues.
 */

export type RuleKind = "model_sql" | "schema_yml" | "snapshot" | "any"

export interface RuleExample {
  add?: string // text treated as added (+) lines
  remove?: string // text treated as removed (-) lines
  newSql?: string // overrides the whole-file SQL (defaults to add)
  path?: string // overrides the file path (for pathGlob rules)
}

export interface Rule {
  id: string
  category: ReviewCategory
  severity: Severity
  title: string
  body: string
  /** at least one match condition; all present conditions must hold (AND). */
  added?: RegExp
  removed?: RegExp
  newSql?: RegExp
  absentNewSql?: RegExp
  /** drop a candidate added-line match if it ALSO matches this (false-positive guard). */
  unless?: RegExp
  kind?: RuleKind
  pathGlob?: RegExp
  example: RuleExample
  counter?: RuleExample
}

function modelName(p: string): string {
  return path.basename(p).replace(/\.(sql|py)$/i, "")
}

function stripComments(s: string): string {
  return s
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/--[^\n]*/g, " ")
    .replace(/\{#[\s\S]*?#\}/g, " ")
}

export interface RuleInput {
  file: ChangedFile
  newSql: string
  added: string[]
  removed: string[]
}

/** True when the rule matches the change. */
export function ruleMatches(rule: Rule, input: RuleInput): boolean {
  const kind = classifyDbtFile(input.file.path)
  const wantKind = rule.kind ?? "model_sql"
  if (wantKind !== "any" && kind !== wantKind) return false
  if (rule.pathGlob && !rule.pathGlob.test(input.file.path)) return false

  // Relevance gate: a rule only fires when its signal is in THE DIFF, never on
  // an unrelated edit to a matching file. added/removed are diff-anchored by
  // construction; a `newSql` (whole-file) condition must also appear in the
  // changed lines to count as relevant. `absentNewSql` is a whole-file guard.
  const diffText = stripComments([...input.added, ...input.removed].join("\n"))
  let relevant = false
  if (rule.added) {
    const hit = input.added.some((l) => {
      const s = stripComments(l)
      return rule.added!.test(s) && !(rule.unless && rule.unless.test(s))
    })
    if (!hit) return false
    relevant = true
  }
  if (rule.removed) {
    if (!input.removed.some((l) => rule.removed!.test(stripComments(l)))) return false
    relevant = true
  }
  if (rule.newSql) {
    if (!rule.newSql.test(stripComments(input.newSql))) return false
    if (rule.newSql.test(diffText)) relevant = true
  }
  if (rule.absentNewSql) {
    if (rule.absentNewSql.test(stripComments(input.newSql))) return false
  }
  return relevant
}

/** Evaluate the catalog against a changed file. */
export function evaluateCatalog(
  file: ChangedFile,
  newSql: string,
  added: string[],
  removed: string[],
  rubric: Rubric,
): Finding[] {
  const input: RuleInput = { file, newSql, added, removed }
  const model = modelName(file.path)
  const out: Finding[] = []
  for (const rule of CATALOG) {
    if (!ruleMatches(rule, input)) continue
    const f = makeFinding({
      severity: clampSeverity(rule.category, rule.severity, "high"),
      category: rule.category,
      title: `${model}: ${rule.title}`,
      body: rule.body,
      file: file.path,
      model,
      confidence: "high",
      evidence: { tool: "rule-catalog", result: { rule: rule.id } },
      ruleKey: `${rule.category}:${rule.id}`,
    })
    if (!exclusionReason(f, rubric)) out.push(f)
  }
  return out
}

/** Build a RuleInput from an example (for the catalog self-test). */
export function inputFromExample(ex: RuleExample, kind: RuleKind = "model_sql"): RuleInput {
  const defaultPath =
    kind === "schema_yml" ? "models/marts/_models.yml" : kind === "snapshot" ? "snapshots/s.sql" : "models/marts/m.sql"
  const file: ChangedFile = { path: ex.path ?? defaultPath, status: "modified" }
  const added = ex.add ? ex.add.split("\n") : []
  const removed = ex.remove ? ex.remove.split("\n") : []
  const newSql = ex.newSql ?? ex.add ?? ""
  return { file, newSql, added, removed }
}

// ===========================================================================
// RULE CATALOG — grouped by concern. Each entry is a real-world review catch.
// ===========================================================================

const r = (
  id: string,
  category: ReviewCategory,
  severity: Severity,
  title: string,
  body: string,
  match: Pick<Rule, "added" | "removed" | "newSql" | "absentNewSql" | "unless" | "kind" | "pathGlob">,
  example: RuleExample,
  counter?: RuleExample,
): Rule => ({ id, category, severity, title, body, ...match, example, counter })

export const CATALOG: Rule[] = []

const CORRECTNESS: Rule[] = [
  r(
    "not-exists-suggested",
    "sql_correctness",
    "suggestion",
    "consider NOT EXISTS over NOT IN",
    "Prefer NOT EXISTS / LEFT JOIN … IS NULL; NOT IN breaks on NULLs and is slower.",
    { added: /\bnot\s+in\s*\(/i },
    { add: "where id not in (1,2,3)" },
    { add: "where id in (1,2,3)" },
  ),
  r(
    "in-subquery-large",
    "warehouse_cost",
    "suggestion",
    "IN (subquery) — consider a semi-join",
    "A correlated/large IN-subquery is often better as an EXISTS or JOIN for the optimizer.",
    { added: /\bin\s*\(\s*select\b/i },
    { add: "where id in (select id from x)" },
    { add: "where id in (1,2)" },
  ),
  r(
    "scalar-subquery-select",
    "warehouse_cost",
    "suggestion",
    "scalar subquery in SELECT runs per row",
    "A `(select …)` in the SELECT list can execute per output row; a JOIN is usually cheaper.",
    { added: /select[^;]*,\s*\(\s*select\b/i },
    { add: "select a, (select max(b) from t) from x" },
    { add: "select a, b from x" },
  ),
  r(
    "union-not-all",
    "warehouse_cost",
    "suggestion",
    "UNION dedups — use UNION ALL if disjoint",
    "`UNION` adds a distinct pass; if inputs can't overlap, `UNION ALL` is far cheaper.",
    { added: /\bunion\b(?!\s+all)/i },
    { add: "select 1 union select 2" },
    { add: "select 1 union all select 2" },
  ),
  r(
    "intersect-perf",
    "warehouse_cost",
    "suggestion",
    "INTERSECT/EXCEPT can be expensive",
    "Set operators sort/hash both sides; confirm a join wouldn't be clearer and cheaper.",
    { added: /\b(intersect|except|minus)\b/i },
    { add: "select a from x except select a from y" },
    { add: "select a from x" },
  ),
  r(
    "having-row-filter",
    "sql_correctness",
    "suggestion",
    "row predicate in HAVING belongs in WHERE",
    "Filtering non-aggregated columns in HAVING is slower and often a bug; move to WHERE.",
    { added: /\bhaving\b.*(=|<|>|like)/i, unless: /\b(count|sum|avg|min|max)\s*\(/i },
    { add: "having status = 'x'" },
    { add: "having count(*) > 1" },
  ),
  r(
    "distinct-and-group-by",
    "sql_correctness",
    "suggestion",
    "DISTINCT together with GROUP BY is redundant",
    "Using DISTINCT on an already-grouped query is redundant and signals confusion about grain.",
    { newSql: /select\s+distinct[\s\S]*\bgroup\s+by\b/i },
    { add: "select distinct a, count(*) from t group by a" },
    { add: "select a, count(*) from t group by a" },
  ),
  r(
    "count-star-nullable",
    "sql_correctness",
    "suggestion",
    "COUNT(col) skips NULLs — confirm intent",
    "`COUNT(col)` ignores NULLs while `COUNT(*)` counts rows; make sure the right one is used.",
    { added: /\bcount\s*\(\s*(?!distinct|\*)[a-z_]/i },
    { add: "select count(amount) from t" },
    { add: "select count(*) from t" },
  ),
  r(
    "nested-aggregate",
    "sql_correctness",
    "warning",
    "nested aggregate is invalid / needs a subquery",
    "Aggregates can't be nested directly (e.g. SUM(COUNT(...))); pre-aggregate in a CTE.",
    { added: /\b(sum|avg|min|max)\s*\(\s*(count|sum|avg|min|max)\s*\(/i },
    { add: "select sum(count(id)) from t" },
    { add: "select sum(amount) from t" },
  ),
  r(
    "group-by-positional",
    "sql_quality",
    "suggestion",
    "GROUP BY positional refs are fragile",
    "`GROUP BY 1,2` breaks silently when the SELECT list reorders; group by explicit names.",
    { added: /\bgroup\s+by\s+\d+(\s*,\s*\d+)+/i },
    { add: "group by 1, 2" },
    { add: "group by customer_id" },
  ),
  r(
    "order-by-positional",
    "sql_quality",
    "suggestion",
    "ORDER BY positional refs are fragile",
    "`ORDER BY 1` breaks when columns reorder; order by explicit names.",
    { added: /\border\s+by\s+\d+/i },
    { add: "order by 1" },
    { add: "order by created_at" },
  ),
  r(
    "select-into",
    "sql_correctness",
    "critical",
    "SELECT INTO / CREATE TABLE inside a model",
    "Models must be a single SELECT — dbt owns materialization. Remove the DDL.",
    { added: /\b(select\s+[^;]*\binto\b|create\s+table)\b/i },
    { add: "select * into new_t from t" },
    { add: "select * from t" },
  ),
  r(
    "temp-table",
    "sql_correctness",
    "warning",
    "temp table created in a model",
    "Creating #temp/temporary tables in a model bypasses dbt's DAG and materialization.",
    { added: /\bcreate\s+(temp|temporary|#)/i },
    { add: "create temp table tmp as select 1" },
    { add: "with tmp as (select 1)" },
  ),
  r(
    "reserved-word-alias",
    "sql_quality",
    "suggestion",
    "alias uses a reserved word",
    "Aliasing a column `as order`/`as table`/`as select` needs quoting and breaks across warehouses.",
    { added: /\bas\s+(order|table|select|from|group|user|case|date)\b/i },
    { add: "select x as order" },
    { add: "select x as order_amount" },
  ),
]

const NULLS: Rule[] = [
  r(
    "coalesce-mismatched-type",
    "sql_correctness",
    "suggestion",
    "COALESCE with mismatched types",
    "`coalesce(num, 'n/a')` mixes types and errors or implicitly casts; keep branches same-typed.",
    { added: /coalesce\s*\(\s*(\d+\s*,\s*'|'[^']*'\s*,\s*\d)/i },
    { add: "coalesce(0, 'none')" },
    { add: "coalesce(amount, 0)" },
  ),
  r(
    "nullif-zero-missing",
    "sql_correctness",
    "suggestion",
    "division should guard zero with NULLIF",
    "Wrap denominators in `nullif(x,0)` (or safe_divide) to avoid divide-by-zero.",
    { added: /\/\s*(sum|count|[a-z_][\w.]*)\b/i, unless: /nullif|safe_divide|\/\s*\d/i },
    { add: "select a / count(id)" },
    { add: "select a / nullif(b,0)" },
  ),
  r(
    "isnull-nonportable",
    "sql_quality",
    "suggestion",
    "ISNULL/NVL is dialect-specific — prefer COALESCE",
    "`ISNULL`/`NVL` aren't portable across warehouses; `COALESCE` is standard.",
    { added: /\b(isnull|nvl)\s*\(/i },
    { add: "select isnull(a, 0)" },
    { add: "select coalesce(a, 0)" },
  ),
  r(
    "null-concat",
    "sql_correctness",
    "suggestion",
    "string concat with a possibly-NULL operand",
    "In many dialects `'x' || null` is NULL; concatenating a nullable column can blank the result.",
    { added: /\|\|/ },
    { add: "select first_name || last_name" },
    { add: "select a + b" },
  ),
]

const DATETIME: Rule[] = [
  r(
    "now-in-filter",
    "idempotency",
    "warning",
    "current date/time in a filter — sliding window",
    "A `now()`/`current_date` predicate makes the result depend on run time (non-idempotent).",
    { added: /\bwhere\b[^;]*\b(current_date|current_timestamp|now|getdate|sysdate)\b/i },
    { add: "where created_at > current_date - 7" },
    { add: "where created_at > '2024-01-01'" },
  ),
  r(
    "dateadd-from-now",
    "idempotency",
    "warning",
    "DATEADD/INTERVAL from current time",
    "Computing windows from `now()` shifts row membership every run; anchor to a var/column.",
    { added: /(dateadd|date_add|date_sub|interval)[^;]*\b(current_date|current_timestamp|now|getdate)\b/i },
    { add: "where ts > dateadd(day,-7,current_date)" },
    { add: "where ts > dateadd(day,-7,'2024-01-01')" },
  ),
  r(
    "timezone-naive-now",
    "sql_correctness",
    "suggestion",
    "naive now() ignores timezone",
    "Bare `now()`/`current_timestamp` uses session TZ; be explicit for cross-region correctness.",
    { added: /\bcurrent_timestamp\b(?!\s*\(\s*\))/i },
    { add: "select current_timestamp" },
    { add: "select current_timestamp() as _loaded_at" },
  ),
  r(
    "string-date-compare",
    "sql_correctness",
    "suggestion",
    "comparing a date column to a string literal",
    "Relying on implicit string→date casts is fragile; cast explicitly to date/timestamp.",
    { added: /\b\w*(date|_at|_ts)\b\s*(=|>|<|>=|<=)\s*'\d{4}\/\d/i },
    { add: "where order_date >= '2024/01/01'" },
    { add: "where order_date >= date '2024-01-01'" },
  ),
  r(
    "extract-on-partition",
    "warehouse_cost",
    "suggestion",
    "EXTRACT/DATE_PART on a date column in WHERE",
    "Wrapping the date column in EXTRACT/DATE_PART defeats partition pruning; use a range.",
    { added: /\bwhere\b[^;]*\b(extract|date_part)\s*\(/i },
    { add: "where extract(month from d) = 1" },
    { add: "where d >= '2024-01-01'" },
  ),
  r(
    "datediff-arg-order",
    "sql_correctness",
    "suggestion",
    "verify DATEDIFF argument order",
    "DATEDIFF arg order differs by warehouse (start,end vs end,start) — sign bugs are common.",
    { added: /\bdatediff\s*\(/i },
    { add: "select datediff(day, a, b)" },
    { add: "select date_diff_safe(a,b)" },
  ),
]

const TYPES: Rule[] = [
  r(
    "implicit-cast-compare",
    "sql_correctness",
    "suggestion",
    "implicit type cast in comparison",
    "Comparing a string column to a number (or vice-versa) forces an implicit cast and can mis-match.",
    { added: /\b\w+_(id|code|zip)\b\s*=\s*\d+/i },
    { add: "where zip_code = 90210" },
    { add: "where zip_code = '90210'" },
  ),
  r(
    "cast-float-to-int",
    "sql_correctness",
    "suggestion",
    "cast to INT truncates, not rounds",
    "`cast(x as int)` truncates toward zero; use round()/floor() if rounding is intended.",
    { added: /cast\s*\([^)]*\bas\s+(int|integer|int64|smallint)\b/i },
    { add: "cast(amount as int)" },
    { add: "cast(amount as numeric)" },
  ),
  r(
    "varchar-fixed-size",
    "contract_violation",
    "suggestion",
    "fixed VARCHAR(n) can truncate",
    "`varchar(n)` silently truncates longer strings on some warehouses; prefer unbounded string.",
    { added: /\b(varchar|char)\s*\(\s*\d+\s*\)/i },
    { add: "cast(name as varchar(20))" },
    { add: "cast(name as string)" },
  ),
  r(
    "boolean-as-int",
    "sql_quality",
    "suggestion",
    "boolean stored as 0/1 int",
    "Encoding booleans as 0/1 loses type safety; use a real boolean.",
    { added: /\bcase\s+when\b[^;]*\bthen\s+1\b[^;]*\belse\s+0\b/i },
    { add: "case when x then 1 else 0 end" },
    { add: "case when x then 'a' else 'b' end" },
  ),
  r(
    "string-trim-missing",
    "sql_quality",
    "suggestion",
    "join/compare on un-trimmed string",
    "Comparing raw strings without trim()/lower() causes silent mismatches on whitespace/case.",
    { added: /\bon\s+\w+\.\w*(name|email|code)\b\s*=\s*\w+\.\w/i },
    { add: "on a.email = b.email" },
    { add: "on lower(a.email) = lower(b.email)" },
  ),
]

const JOINS: Rule[] = [
  r(
    "right-join",
    "sql_quality",
    "suggestion",
    "RIGHT JOIN is hard to read — prefer LEFT",
    "RIGHT JOINs are error-prone to reason about; reorder tables and use LEFT JOIN.",
    { added: /\bright\s+(outer\s+)?join\b/i },
    { add: "right join orders o on o.id = c.id" },
    { add: "left join orders o on o.id = c.id" },
  ),
  r(
    "full-outer-join",
    "join_risk",
    "suggestion",
    "FULL OUTER JOIN — verify both-null rows handled",
    "FULL OUTER JOINs produce rows with NULLs on either side; coalesce keys and confirm grain.",
    { added: /\bfull\s+(outer\s+)?join\b/i },
    { add: "full outer join b on a.id=b.id" },
    { add: "inner join b on a.id=b.id" },
  ),
  r(
    "join-no-on",
    "join_risk",
    "critical",
    "JOIN without ON / USING — cartesian product",
    "A JOIN with no ON clause is a cross join; add the join key.",
    { added: /\bjoin\s+[\w.`'{}() ]+\s+(where|group|order|having|;|$)/i },
    { add: "join orders where x = 1" },
    { add: "join orders on a=b" },
  ),
  r(
    "using-join",
    "join_risk",
    "suggestion",
    "JOIN USING can hide NULL/ambiguity",
    "`USING(col)` joins on equality and merges columns; an explicit `ON` is clearer and safer.",
    { added: /\bjoin\b[^;]*\busing\s*\(/i },
    { add: "join b using (id)" },
    { add: "join b on a.id=b.id" },
  ),
  r(
    "multiple-left-joins",
    "fanout",
    "suggestion",
    "several LEFT JOINs to detail tables — fan-out risk",
    "Chaining LEFT JOINs to one-to-many tables multiplies rows; pre-aggregate before joining.",
    { newSql: /left\s+join[\s\S]*left\s+join[\s\S]*left\s+join/i },
    { add: "a left join b on x left join c on y left join d on z" },
    { add: "a left join b on x" },
  ),
  r(
    "join-on-cast",
    "join_risk",
    "suggestion",
    "join key wrapped in CAST/function",
    "Casting a column inside the ON clause defeats key pruning and signals a type mismatch.",
    { added: /\bon\b[^;]*\bcast\s*\(/i },
    { add: "on cast(a.id as string) = b.id" },
    { add: "on a.id = b.id" },
  ),
  r(
    "join-or-condition",
    "join_risk",
    "warning",
    "OR in a join condition — explosive/slow",
    "`JOIN … ON a=b OR c=d` often produces a near-cartesian and disables hash joins. Split into UNION.",
    { added: /\bon\b[^;]*\bor\b/i },
    { add: "on a.id=b.id or a.alt=b.alt" },
    { add: "on a.id=b.id and a.k=b.k" },
  ),
  r(
    "lateral-join",
    "warehouse_cost",
    "suggestion",
    "LATERAL/CROSS APPLY runs per row",
    "Lateral joins execute the subquery per outer row; verify it's necessary and bounded.",
    { added: /\b(cross\s+apply|outer\s+apply|lateral)\b/i },
    { add: "cross apply (select 1) x" },
    { add: "join x on 1=1" },
  ),
  r(
    "unqualified-column-multi-table",
    "sql_quality",
    "suggestion",
    "unqualified column with multiple tables",
    "With joins present, unqualified columns are ambiguous and break when both sides add the name.",
    { newSql: /select\s+\w+\s*,[\s\S]*\bjoin\b/i },
    { add: "select id, name from a join b on a.k=b.k" },
    { add: "select a.id from a join b on a.k=b.k" },
  ),
  r(
    "self-join-no-inequality",
    "fanout",
    "suggestion",
    "self-join without an inequality may duplicate",
    "Self-joining on equality alone yields mirror/self pairs; add `a.id < b.id` to dedupe.",
    { newSql: /from\s+(\w+)\s+\w+[\s\S]*join\s+\1\s+/i },
    { add: "from t a join t b on a.k=b.k" },
    { add: "from t a join u b on a.k=b.k" },
  ),
]

const AGG: Rule[] = [
  r(
    "avg-of-avg",
    "sql_correctness",
    "warning",
    "AVG of an AVG is statistically wrong",
    "Averaging pre-averaged values isn't the overall average; aggregate from the base grain.",
    { added: /\bavg\s*\(\s*avg_/i },
    { add: "select avg(avg_order_value)" },
    { add: "select avg(order_value)" },
  ),
  r(
    "sum-of-ratio",
    "sql_correctness",
    "suggestion",
    "SUM of a ratio/percentage is meaningless",
    "Summing rates/percentages double-counts; sum numerator and denominator then divide.",
    { added: /\bsum\s*\(\s*\w*(rate|pct|percent|ratio)\b/i },
    { add: "select sum(conversion_rate)" },
    { add: "select sum(amount)" },
  ),
  r(
    "count-distinct-multiple-cols",
    "sql_correctness",
    "suggestion",
    "COUNT(DISTINCT a, b) portability",
    "Multi-column COUNT(DISTINCT) isn't supported on all warehouses; concat or use a subquery.",
    { added: /count\s*\(\s*distinct\s+[^),]+,/i },
    { add: "count(distinct a, b)" },
    { add: "count(distinct a)" },
  ),
  r(
    "agg-without-group",
    "sql_correctness",
    "suggestion",
    "mixing aggregate and non-aggregate without GROUP BY",
    "Selecting a bare column alongside an aggregate with no GROUP BY errors or picks an arbitrary row.",
    { newSql: /select\s+\w+\s*,\s*(sum|count|avg|max|min)\s*\([\s\S]*\bfrom\b/i, absentNewSql: /\bgroup\s+by\b/i },
    { add: "select customer_id, sum(amount) from t" },
    { add: "select sum(amount) from t" },
  ),
  r(
    "string-agg-no-order",
    "sql_correctness",
    "suggestion",
    "STRING_AGG/LISTAGG without ORDER BY",
    "Aggregating strings without an ORDER BY gives non-deterministic concatenation order.",
    { added: /\b(string_agg|listagg|group_concat|array_agg)\s*\(/i, unless: /order\s+by/i },
    { add: "string_agg(name)" },
    { add: "string_agg(name order by name)" },
  ),
  r(
    "min-max-on-string-date",
    "sql_correctness",
    "suggestion",
    "MIN/MAX on a string date compares lexically",
    "MIN/MAX over a string-typed date compares text, not chronology; cast to date first.",
    { added: /\b(min|max)\s*\(\s*\w*date_str/i },
    { add: "max(date_str)" },
    { add: "max(order_date)" },
  ),
  r(
    "filter-after-agg",
    "sql_correctness",
    "suggestion",
    "aggregate filtered in WHERE instead of HAVING",
    "You can't filter an aggregate in WHERE; aggregate conditions belong in HAVING.",
    { added: /\bwhere\b[^;]*\b(count|sum|avg)\s*\(/i },
    { add: "where sum(x) > 10" },
    { add: "having sum(x) > 10" },
  ),
  r(
    "percentile-no-within",
    "sql_correctness",
    "suggestion",
    "PERCENTILE_CONT without WITHIN GROUP",
    "Ordered-set aggregates need `WITHIN GROUP (ORDER BY …)`; missing it errors or misorders.",
    { added: /percentile_(cont|disc)\s*\(/i, unless: /within\s+group/i },
    { add: "percentile_cont(0.5)" },
    { add: "percentile_cont(0.5) within group (order by x)" },
  ),
]

const WINDOWS: Rule[] = [
  r(
    "running-total-no-order",
    "sql_correctness",
    "warning",
    "running aggregate window with no ORDER BY",
    "A cumulative `sum() over (partition by …)` without ORDER BY isn't a running total — add ORDER BY.",
    { added: /\b(sum|count|avg)\s*\([^)]*\)\s*over\s*\(\s*partition[^)]*\)/i, unless: /order\s+by/i },
    { add: "sum(x) over (partition by id)" },
    { add: "sum(x) over (partition by id order by d)" },
  ),
  r(
    "rows-vs-range",
    "sql_correctness",
    "suggestion",
    "RANGE frame with ties double-counts — use ROWS",
    "`RANGE BETWEEN` includes peer rows with equal ORDER BY values; use `ROWS` for true running totals.",
    { added: /\brange\s+between\b/i },
    { add: "over (order by d range between unbounded preceding and current row)" },
    { add: "over (order by d rows between unbounded preceding and current row)" },
  ),
  r(
    "lag-lead-no-default",
    "sql_correctness",
    "suggestion",
    "LAG/LEAD without a default yields NULL at edges",
    "First/last rows get NULL from LAG/LEAD; pass a default if downstream math can't handle NULL.",
    { added: /\b(lag|lead)\s*\(\s*[^,)]+\s*\)/i },
    { add: "lag(amount) over (order by d)" },
    { add: "lag(amount, 1, 0) over (order by d)" },
  ),
  r(
    "qualify-without-window",
    "sql_quality",
    "suggestion",
    "QUALIFY without a window function",
    "`QUALIFY` filters window results; without a window function it's likely a misplaced WHERE/HAVING.",
    { newSql: /\bqualify\b/i, absentNewSql: /\bover\s*\(/i },
    { add: "select a from t qualify x = 1" },
    { add: "select a from t qualify row_number() over (order by d) = 1" },
  ),
  r(
    "distinct-with-window",
    "sql_correctness",
    "warning",
    "DISTINCT with a window function",
    "DISTINCT runs after window functions, so it dedupes post-computation — usually not intended.",
    { newSql: /select\s+distinct[\s\S]*\bover\s*\(/i },
    { add: "select distinct a, row_number() over (order by d) from t" },
    { add: "select a, row_number() over (order by d) from t" },
  ),
]

const PERF: Rule[] = [
  r(
    "count-distinct-large",
    "warehouse_cost",
    "suggestion",
    "COUNT(DISTINCT) is expensive at scale",
    "Exact distinct counts need a global sort/hash; use APPROX_COUNT_DISTINCT/HLL when tolerable.",
    { added: /count\s*\(\s*distinct/i },
    { add: "count(distinct user_id)" },
    { add: "count(user_id)" },
  ),
  r(
    "order-by-in-cte",
    "warehouse_cost",
    "suggestion",
    "ORDER BY inside a CTE/subquery is ignored",
    "Ordering inside a CTE has no guaranteed effect downstream and just adds a sort cost.",
    { newSql: /\bas\s*\(\s*select[\s\S]*?\border\s+by\b[\s\S]*?\)/i },
    { add: "with x as (select a from t order by a) select * from x" },
    { add: "with x as (select a from t) select * from x" },
  ),
  r(
    "function-on-join-key",
    "warehouse_cost",
    "suggestion",
    "function on a filter column blocks pruning",
    "Wrapping a filtered column in lower()/upper()/substr defeats clustering/partition pruning.",
    { added: /\bwhere\b[^;]*\b(lower|upper|substr|substring|trim|replace)\s*\(/i },
    { add: "where lower(email) = 'x'" },
    { add: "where email = 'x'" },
  ),
  r(
    "implicit-cross-join-comma",
    "join_risk",
    "warning",
    "comma-separated tables in FROM (implicit cross join)",
    "`from a, b` cross-joins unless a WHERE ties them — fragile; use explicit JOIN … ON.",
    { added: /\bfrom\s+[\w.`{}']+(\s+\w+)?\s*,\s*[\w.`{}']+/i },
    { add: "from orders o, customers c" },
    { add: "from orders o" },
  ),
  r(
    "select-star-in-cte-final",
    "warehouse_cost",
    "suggestion",
    "SELECT * in final projection",
    "A trailing `select *` carries every upstream column forward, bloating the model and storage.",
    { added: /^\s*select\s+\*\s*$/i },
    { add: "select *" },
    { add: "select id, name" },
  ),
  r(
    "large-in-list",
    "warehouse_cost",
    "suggestion",
    "very large literal IN-list",
    "A huge `IN (… , … , …)` literal list is slow and unmaintainable; join to a seed/ref instead.",
    { added: /\bin\s*\([^)]*,[^)]*,[^)]*,[^)]*,[^)]*,/i },
    { add: "where id in (1,2,3,4,5,6)" },
    { add: "where id in (1,2)" },
  ),
  r(
    "nested-subqueries-deep",
    "warehouse_cost",
    "suggestion",
    "deeply nested subqueries hurt readability/plans",
    "Several nested `(select … (select …))` levels are hard to optimize; flatten into CTEs.",
    { newSql: /\(\s*select[\s\S]*\(\s*select[\s\S]*\(\s*select/i },
    { add: "select (select (select (select 1)))" },
    { add: "select a from t" },
  ),
  r(
    "distinct-star",
    "warehouse_cost",
    "warning",
    "SELECT DISTINCT * scans + sorts everything",
    "`select distinct *` reads all columns and sorts the whole set — almost always the wrong fix.",
    { added: /select\s+distinct\s+\*/i },
    { add: "select distinct * from t" },
    { add: "select distinct id from t" },
  ),
  r(
    "regexp-heavy",
    "warehouse_cost",
    "suggestion",
    "regex function on a filtered/large column",
    "REGEXP_* over big tables is CPU-heavy; prefer LIKE/anchored patterns where possible.",
    { added: /\b(regexp_contains|regexp_like|rlike|regexp_extract|regexp_matches)\s*\(/i },
    { add: "where regexp_contains(name, 'x')" },
    { add: "where name like 'x%'" },
  ),
  r(
    "cartesian-via-union-subquery",
    "warehouse_cost",
    "suggestion",
    "scalar aggregate cross-joined to every row",
    "Cross-joining a 1-row aggregate to a big table is fine, but verify it isn't an accidental fan-out.",
    { added: /\bcross\s+join\s*\(\s*select\b/i },
    { add: "cross join (select max(d) from t)" },
    { add: "join (select id from t) x on x.id=a.id" },
  ),
]

const MATERIALIZATION: Rule[] = [
  r(
    "ephemeral-with-joins",
    "materialization",
    "suggestion",
    "ephemeral model with heavy joins is inlined everywhere",
    "An `ephemeral` model is inlined into every consumer; with joins that's repeated recompute. Prefer view/table.",
    { newSql: /materialized\s*[=:]\s*['"]?ephemeral[\s\S]*\bjoin\b/i },
    { add: "{{ config(materialized='ephemeral') }} select * from a join b on a.k=b.k" },
    { add: "{{ config(materialized='view') }} select * from a join b on a.k=b.k" },
  ),
  r(
    "staging-as-table",
    "materialization",
    "suggestion",
    "staging model materialized as table",
    "Staging models are usually views/ephemeral; a `table` here adds storage + a full rebuild each run.",
    { newSql: /materialized\s*[=:]\s*['"]?table/i, pathGlob: /(^|\/)stg_|(^|\/)staging\//i },
    {
      add: "{{ config(materialized='table') }} select 1",
      newSql: "{{ config(materialized='table') }} select 1",
      path: "models/staging/stg_x.sql",
    },
    {
      add: "{{ config(materialized='view') }} select 1",
      newSql: "{{ config(materialized='view') }} select 1",
      path: "models/staging/stg_x.sql",
    },
  ),
  r(
    "on-schema-change-ignore",
    "contract_violation",
    "warning",
    "incremental on_schema_change='ignore'",
    "With `on_schema_change='ignore'`, added/reordered columns silently misalign on append. Use 'sync_all_columns' or 'append_new_columns'.",
    { added: /on_schema_change\s*[=:]\s*['"]ignore/i },
    { add: "on_schema_change='ignore'" },
    { add: "on_schema_change='sync_all_columns'" },
  ),
  r(
    "delete-insert-no-key",
    "dedup",
    "warning",
    "delete+insert incremental without unique_key",
    "`incremental_strategy='delete+insert'` with no `unique_key` can't delete matched rows — duplicates accrue.",
    { newSql: /delete\s*\+\s*insert/i, absentNewSql: /unique_key/i },
    { add: "incremental_strategy='delete+insert' select 1", newSql: "incremental_strategy='delete+insert' select 1" },
    {
      add: "incremental_strategy='delete+insert' unique_key='id'",
      newSql: "incremental_strategy='delete+insert' unique_key='id'",
    },
  ),
  r(
    "merge-no-key",
    "dedup",
    "warning",
    "merge incremental without unique_key",
    "`incremental_strategy='merge'` needs a `unique_key` to match rows; without it it appends and duplicates.",
    { newSql: /incremental_strategy\s*[=:]\s*['"]merge/i, absentNewSql: /unique_key/i },
    { add: "incremental_strategy='merge' select 1", newSql: "incremental_strategy='merge' select 1" },
    { add: "incremental_strategy='merge' unique_key='id'", newSql: "incremental_strategy='merge' unique_key='id'" },
  ),
  r(
    "values-inline-seed",
    "sql_quality",
    "suggestion",
    "inline VALUES list should be a seed",
    "A hardcoded `(values …)` lookup belongs in a `seeds/` CSV, not inline in a model.",
    { added: /\bfrom\s*\(\s*values\b/i },
    { add: "from (values (1),(2)) as t(x)" },
    { add: "from {{ ref('seed_x') }}" },
  ),
  r(
    "pre-hook-dml",
    "sql_correctness",
    "warning",
    "destructive pre/post-hook",
    "A `pre_hook`/`post_hook` running DELETE/TRUNCATE/DROP runs every build and can destroy data.",
    { added: /(pre_hook|post_hook)[\s\S]*\b(delete|truncate|drop)\b/i },
    { add: "post_hook='truncate table x'" },
    { add: "post_hook='grant select on x to role'" },
  ),
  r(
    "table-no-cluster-large",
    "warehouse_cost",
    "suggestion",
    "large table materialization without clustering/partitioning",
    "A `table`/incremental over a big source with no partition_by/cluster_by scans fully on read. Add partitioning.",
    {
      newSql: /materialized\s*[=:]\s*['"]?(table|incremental)/i,
      absentNewSql: /(partition_by|cluster_by|partitioned\s+by|clustered\s+by)/i,
      pathGlob: /(^|\/)(marts|fct_|fact_)/i,
    },
    {
      add: "{{ config(materialized='incremental') }} select 1 from fct",
      newSql: "{{ config(materialized='incremental') }} select 1 from fct",
    },
    {
      add: "{{ config(materialized='incremental', partition_by={'field':'d'}) }} select 1",
      newSql: "{{ config(materialized='incremental', partition_by={'field':'d'}) }} select 1",
    },
  ),
]

const DBT_CONV: Rule[] = [
  r(
    "ref-double-quotes",
    "sql_quality",
    "suggestion",
    "ref() uses double quotes",
    "dbt convention is single-quoted `ref('model')`; double quotes are inconsistent and can confuse linters.",
    { added: /\{\{\s*ref\(\s*"/i },
    { add: 'from {{ ref("x") }}' },
    { add: "from {{ ref('x') }}" },
  ),
  r(
    "information-schema",
    "sql_quality",
    "warning",
    "querying INFORMATION_SCHEMA directly",
    "Reading INFORMATION_SCHEMA/SVV_* in a model bypasses the dbt DAG and is environment-fragile.",
    { added: /\bfrom\s+[`"]?information_schema\b|\bfrom\s+svv_/i },
    { add: "from information_schema.tables" },
    { add: "from {{ ref('x') }}" },
  ),
  r(
    "run-query-parse",
    "sql_quality",
    "warning",
    "run_query()/statement at parse time",
    "`run_query`/`statement` execute against the warehouse during compile — slow, fragile, and needs a live DB.",
    { added: /\b(run_query|statement)\s*\(/i },
    { add: "{% set r = run_query('select 1') %}" },
    { add: "{{ ref('x') }}" },
  ),
  r(
    "adapter-call",
    "sql_quality",
    "suggestion",
    "adapter.* introspection in a model",
    "`adapter.get_columns_in_relation`/`adapter.dispatch` hit the warehouse at compile; isolate in macros.",
    { added: /\{\{[^}]*adapter\.\w+/i },
    { add: "{{ adapter.get_columns_in_relation(this) }}" },
    { add: "{{ ref('x') }}" },
  ),
  r(
    "dbt-utils-star",
    "warehouse_cost",
    "suggestion",
    "dbt_utils.star() expands to all columns",
    "`dbt_utils.star()` selects every column (like SELECT *), bloating the model and needing a DB at parse.",
    { added: /dbt_utils\.star\s*\(/i },
    { add: "{{ dbt_utils.star(from=ref('x')) }}" },
    { add: "select id, name" },
  ),
  r(
    "env-var-in-model",
    "pii_exposure",
    "suggestion",
    "env_var() inside a model",
    "`{{ env_var(...) }}` in model SQL couples logic to the environment and can leak secrets into compiled code.",
    { added: /\{\{\s*env_var\s*\(/i },
    { add: "where token = '{{ env_var('API_KEY') }}'" },
    { add: "where d > {{ var('cutoff', 0) }}" },
  ),
  r(
    "magic-number",
    "sql_quality",
    "suggestion",
    "magic numeric constant",
    "An unexplained constant (e.g. `* 86400`, `/ 1000000`) hurts readability; name it via a var/CTE.",
    { added: /[*\/]\s*(86400|3600|1000000|604800|1048576)\b/ },
    { add: "select seconds / 86400 as days" },
    { add: "select a / b as r" },
  ),
  r(
    "hardcoded-fx-multiplier",
    "sql_quality",
    "suggestion",
    "hardcoded conversion/multiplier",
    "A literal rate like `* 1.1` (tax/fx) drifts out of date; source it from a seed/var.",
    { added: /[*]\s*1\.\d{1,3}\b/ },
    { add: "select amount * 1.08 as with_tax" },
    { add: "select amount * qty as total" },
  ),
  r(
    "ref-to-source-table",
    "lineage_breakage",
    "warning",
    "ref() pointing at a raw/source table name",
    "Using `ref()` on a source-style name (raw_/src_) suggests a missing `source()`; lineage will be wrong.",
    { added: /\{\{\s*ref\(\s*['"](raw_|src_|source_)/i },
    { add: "from {{ ref('raw_orders') }}" },
    { add: "from {{ source('app','orders') }}" },
  ),
  r(
    "limit-in-subquery-dev",
    "sql_correctness",
    "warning",
    "LIMIT inside a CTE/subquery",
    "A `LIMIT` buried in a CTE caps rows for everything downstream — usually a debugging leftover.",
    { newSql: /\bas\s*\(\s*select[\s\S]*\blimit\s+\d+[\s\S]*\)/i },
    { add: "with x as (select a from t limit 100) select * from x" },
    { add: "with x as (select a from t) select * from x" },
  ),
  r(
    "sample-clause",
    "sql_correctness",
    "warning",
    "TABLESAMPLE / SAMPLE left in model",
    "A `tablesample`/`sample` clause returns a random subset every run — non-deterministic and lossy.",
    { added: /\b(tablesample|sample)\s*\(/i },
    { add: "from t tablesample (10 percent)" },
    { add: "from t" },
  ),
]

const TESTS_CONTRACTS: Rule[] = [
  r(
    "enforced-contract-removed",
    "contract_violation",
    "warning",
    "enforced contract removed",
    "Dropping `enforced: true` removes the schema guarantee downstream consumers rely on.",
    { kind: "schema_yml", removed: /enforced:\s*true/i },
    { remove: "      enforced: true" },
    { remove: "      some_other: true" },
  ),
  r(
    "accepted-values-removed",
    "test_coverage",
    "suggestion",
    "accepted_values test removed",
    "Removing an `accepted_values` test lets unexpected enum values flow through silently.",
    { kind: "schema_yml", removed: /accepted_values/i },
    { remove: "          - accepted_values:" },
    { remove: "          - not_null" },
  ),
  r(
    "yml-data-type-narrowed",
    "contract_violation",
    "warning",
    "contract column data_type narrowed",
    "A contracted `data_type` was changed to a narrower type — truncation/overflow + contract break.",
    {
      kind: "schema_yml",
      removed: /data_type:\s*(numeric|string|bignumeric|float64)/i,
      added: /data_type:\s*(int|smallint|varchar\(|number\(\d)/i,
    },
    { add: "        data_type: int64", remove: "        data_type: numeric" },
    { add: "        data_type: numeric", remove: "        data_type: string" },
  ),
  r(
    "yml-column-removed",
    "contract_violation",
    "warning",
    "column removed from schema.yml",
    "Removing a column entry from a contracted model breaks the contract and any downstream ref to it.",
    { kind: "schema_yml", removed: /^\s*-\s*name:\s*\w+/i },
    { remove: "      - name: order_id" },
    { remove: "    description: docs" },
  ),
  r(
    "test-severity-warn",
    "test_coverage",
    "suggestion",
    "test downgraded to severity: warn",
    "Setting a test to `severity: warn` stops it failing CI — it no longer guards the merge.",
    { kind: "schema_yml", added: /severity:\s*warn/i },
    { add: "          severity: warn" },
    { add: "          severity: error" },
  ),
  r(
    "test-disabled",
    "test_coverage",
    "warning",
    "test disabled (enabled: false)",
    "Disabling a test (`enabled: false`) silently removes its guarantee; confirm it's truly obsolete.",
    { kind: "schema_yml", added: /enabled:\s*false/i },
    { add: "          enabled: false" },
    { add: "          enabled: true" },
  ),
  r(
    "yml-description-removed",
    "sql_quality",
    "suggestion",
    "model/column description removed",
    "Removing documentation reduces discoverability and breaks docs/exposure references.",
    { kind: "schema_yml", removed: /^\s*description:/i },
    { remove: "    description: revenue per day" },
    { remove: "    name: x" },
  ),
  r(
    "source-freshness-removed",
    "freshness",
    "warning",
    "source freshness check removed",
    "Deleting a source `freshness:` block stops stale-data alerts; downstream silently serves old data.",
    { kind: "schema_yml", removed: /freshness:/i },
    { remove: "    freshness:" },
    { remove: "    description: orders" },
  ),
  r(
    "loaded-at-field-removed",
    "freshness",
    "warning",
    "source loaded_at_field removed",
    "Removing `loaded_at_field` disables freshness measurement on the source.",
    { kind: "schema_yml", removed: /loaded_at_field:/i },
    { remove: "    loaded_at_field: _loaded_at" },
    { remove: "    database: prod" },
  ),
  r(
    "relationship-test-removed-yml",
    "test_coverage",
    "warning",
    "relationships (FK) test removed",
    "Dropping a `relationships` test removes referential-integrity checking between models.",
    { kind: "schema_yml", removed: /relationships:/i },
    { remove: "          - relationships:" },
    { remove: "          - not_null" },
  ),
]

const SNAPSHOTS: Rule[] = [
  r(
    "snapshot-select-star",
    "freshness",
    "warning",
    "snapshot uses SELECT * — breaks on schema change",
    "A `select *` snapshot errors or mis-tracks when the source adds/changes a column; select explicit columns.",
    { kind: "snapshot", added: /select\s+\*/i },
    { add: "select * from {{ source('a','b') }}" },
    { add: "select id, status from {{ source('a','b') }}" },
  ),
  r(
    "snapshot-check-no-cols",
    "freshness",
    "warning",
    "check-strategy snapshot without check_cols",
    "A `strategy='check'` snapshot needs `check_cols`; without it changes aren't detected.",
    { kind: "snapshot", newSql: /strategy\s*[=:]\s*['"]check/i, absentNewSql: /check_cols/i },
    { add: "{{ config(strategy='check') }}", newSql: "{{ config(strategy='check') }}" },
    {
      add: "{{ config(strategy='check', check_cols=['status']) }}",
      newSql: "{{ config(strategy='check', check_cols=['status']) }}",
    },
  ),
  r(
    "snapshot-timestamp-no-updated",
    "freshness",
    "warning",
    "timestamp-strategy snapshot without updated_at",
    "A `strategy='timestamp'` snapshot requires `updated_at`; missing it breaks SCD tracking.",
    { kind: "snapshot", newSql: /strategy\s*[=:]\s*['"]timestamp/i, absentNewSql: /updated_at/i },
    { add: "{{ config(strategy='timestamp') }}", newSql: "{{ config(strategy='timestamp') }}" },
    {
      add: "{{ config(strategy='timestamp', updated_at='modified_at') }}",
      newSql: "{{ config(strategy='timestamp', updated_at='modified_at') }}",
    },
  ),
  r(
    "snapshot-hard-deletes",
    "freshness",
    "suggestion",
    "snapshot without invalidate_hard_deletes",
    "Without `invalidate_hard_deletes=true`, rows deleted at source stay 'current' forever in the snapshot.",
    { kind: "snapshot", newSql: /\{%\s*snapshot\b/i, absentNewSql: /invalidate_hard_deletes/i },
    {
      add: "{% snapshot s %}{{ config(strategy='timestamp', updated_at='u') }}",
      newSql: "{% snapshot s %}{{ config(strategy='timestamp', updated_at='u') }}",
    },
    {
      add: "{% snapshot s %}{{ config(invalidate_hard_deletes=true) }}",
      newSql: "{% snapshot s %}{{ config(invalidate_hard_deletes=true) }}",
    },
  ),
]

const SECURITY_PII: Rule[] = [
  r(
    "hardcoded-credential",
    "pii_exposure",
    "critical",
    "hardcoded credential/secret in SQL",
    "A literal password/secret/api_key/token in model SQL leaks into compiled artifacts and git. Use env/secret manager.",
    { added: /\b(password|secret|api_key|apikey|access_token|private_key)\s*[=:]\s*['"][^'"]{4,}/i },
    { add: "where api_key = 'sk-12345abc'" },
    { add: "where d > {{ var('cutoff', 0) }}" },
  ),
  r(
    "select-pii-columns",
    "pii_exposure",
    "warning",
    "PII columns selected",
    "Email/SSN/phone/DOB pulled into a model widens PII exposure; confirm it's needed and masked.",
    { added: /^\s*[\w.]*\b(ssn|social_security|email|phone_number|date_of_birth|passport)\b/i },
    { add: "        c.ssn," },
    { add: "        c.country," },
  ),
  r(
    "pii-concat",
    "pii_exposure",
    "suggestion",
    "concatenating PII fields",
    "Joining first/last name or email into a new field creates derived PII that needs governance.",
    { added: /(first_name\s*\|\||concat\s*\(\s*first_name)/i },
    { add: "first_name || last_name as full_name" },
    { add: "a || b as k" },
  ),
  r(
    "masking-removed",
    "pii_exposure",
    "warning",
    "masking macro/post-hook removed",
    "Removing a masking macro/post-hook re-exposes raw PII on the next rebuild.",
    { removed: /(apply_masking|mask_column|masking_policy)/i },
    { remove: "post_hook=\"{{ apply_masking('email') }}\"" },
    { remove: 'post_hook="grant select"' },
  ),
  r(
    "weak-pii-hash",
    "pii_exposure",
    "suggestion",
    "weak hash (MD5) of PII",
    "MD5/SHA1 of PII is reversible/brute-forceable; use a keyed hash or proper tokenization for anonymization.",
    { added: /\bmd5\s*\(\s*\w*(email|ssn|phone|name)/i },
    { add: "md5(email) as email_hash" },
    { add: "md5(order_id) as k" },
  ),
  r(
    "plaintext-pii-key",
    "pii_exposure",
    "suggestion",
    "surrogate key built from raw PII",
    "Hashing PII into a join key still derives from PII and can correlate individuals; prefer a tokenized id.",
    { added: /generate_surrogate_key\s*\(\s*\[[^\]]*\b(email|ssn|phone)\b/i },
    { add: "{{ dbt_utils.generate_surrogate_key(['email']) }}" },
    { add: "{{ dbt_utils.generate_surrogate_key(['order_id']) }}" },
  ),
]

const BIGQUERY: Rule[] = [
  r(
    "bq-no-partition-filter",
    "warehouse_cost",
    "warning",
    "BigQuery: query on a partitioned table with no partition filter",
    "Without a `_PARTITIONTIME`/partition-column predicate, BigQuery scans the whole table (full cost).",
    {
      added: /from\s+[^;\n]*(events|logs|fct_|fact_|_fct|_fact)/i,
      absentNewSql: /(_partitiontime|_partitiondate|\bwhere\b[\s\S]*(date|_at|created|partition))/i,
    },
    { add: "from `proj`.`ds`.`events_fct`", newSql: "from `proj`.`ds`.`events_fct`" },
    {
      add: "from `proj`.`ds`.`events_fct` where created_at > '2024-01-01'",
      newSql: "from `proj`.`ds`.`events_fct` where created_at > '2024-01-01'",
    },
  ),
  r(
    "bq-wildcard-no-suffix",
    "warehouse_cost",
    "warning",
    "BigQuery: wildcard table without _TABLE_SUFFIX filter",
    "Wildcard tables (`events_*`) scan every shard unless filtered on `_TABLE_SUFFIX`.",
    { added: /from\s+[`"][^`"]*\*[`"]/i, absentNewSql: /_table_suffix/i },
    { add: "from `proj.ds.events_*`", newSql: "from `proj.ds.events_*`" },
    {
      add: "from `proj.ds.events_*` where _table_suffix between '2024' and '2025'",
      newSql: "from `proj.ds.events_*` where _table_suffix between '2024' and '2025'",
    },
  ),
  r(
    "bq-legacy-sql",
    "sql_quality",
    "warning",
    "BigQuery: legacy-SQL syntax",
    "Legacy SQL (`[proj:ds.table]`, `TABLE_DATE_RANGE`) is deprecated; use Standard SQL.",
    { added: /(\[[\w-]+:[\w.]+\]|table_date_range|table_query)/i },
    { add: "from [my-proj:ds.table]" },
    { add: "from `my-proj`.`ds`.`table`" },
  ),
  r(
    "bq-cross-join-unnest",
    "fanout",
    "suggestion",
    "BigQuery: CROSS JOIN UNNEST can explode rows",
    "`CROSS JOIN UNNEST(array)` multiplies rows by array length; confirm the fan-out is intended.",
    { added: /cross\s+join\s+unnest\s*\(/i },
    { add: "cross join unnest(items) as item" },
    { add: "left join unnest(items) as item" },
  ),
  r(
    "bq-safe-cast-missing",
    "sql_correctness",
    "suggestion",
    "BigQuery: CAST may error — consider SAFE_CAST",
    "On dirty data `CAST` throws and fails the whole run; `SAFE_CAST` returns NULL on bad values.",
    { added: /\bcast\s*\(\s*\w+\s+as\s+(int64|numeric|float64|date|timestamp)\b/i, unless: /safe_cast/i },
    { add: "cast(amount as int64)" },
    { add: "safe_cast(amount as int64)" },
  ),
  r(
    "bq-float64-money",
    "sql_correctness",
    "suggestion",
    "BigQuery: FLOAT64 for money loses precision",
    "Use `NUMERIC`/`BIGNUMERIC` for currency; `FLOAT64` introduces rounding error.",
    { added: /cast\s*\(\s*\w*(amount|price|revenue|cost|total)\w*\s+as\s+float64/i },
    { add: "cast(amount as float64)" },
    { add: "cast(amount as numeric)" },
  ),
  r(
    "bq-select-star-replace",
    "sql_quality",
    "suggestion",
    "BigQuery: prefer SELECT * EXCEPT/REPLACE over bare *",
    "If you must use `*`, BigQuery's `* EXCEPT(...)`/`* REPLACE(...)` is safer than a bare star.",
    { added: /select\s+\*\s+from/i, unless: /except\s*\(|replace\s*\(|\{\{/i },
    { add: "select * from t" },
    { add: "select * except(x) from t" },
  ),
  r(
    "bq-generate-array-large",
    "warehouse_cost",
    "suggestion",
    "BigQuery: GENERATE_ARRAY/DATE_ARRAY can be huge",
    "A wide `GENERATE_ARRAY`/`GENERATE_DATE_ARRAY` materializes every element; bound the range.",
    { added: /generate_(date_|timestamp_)?array\s*\(/i },
    { add: "generate_date_array('2000-01-01', current_date)" },
    { add: "from {{ ref('date_spine') }}" },
  ),
  r(
    "bq-datetime-vs-timestamp",
    "sql_correctness",
    "suggestion",
    "BigQuery: DATETIME vs TIMESTAMP confusion",
    "`DATETIME` has no timezone; mixing it with `TIMESTAMP` in comparisons shifts results.",
    { added: /cast\s*\(\s*\w*\s+as\s+datetime\b/i },
    { add: "cast(ts as datetime)" },
    { add: "cast(ts as timestamp)" },
  ),
  r(
    "bq-array-no-offset",
    "sql_correctness",
    "suggestion",
    "BigQuery: array access needs OFFSET/ORDINAL",
    "Indexing an array as `arr[0]` errors in BigQuery; use `arr[OFFSET(0)]` or `[ORDINAL(1)]`.",
    { added: /\b\w+\[\s*\d+\s*\]/ },
    { add: "select items[0]" },
    { add: "select items[offset(0)]" },
  ),
  r(
    "bq-approx-good",
    "warehouse_cost",
    "suggestion",
    "BigQuery: large exact COUNT(DISTINCT) — APPROX is cheaper",
    "On BigQuery, `APPROX_COUNT_DISTINCT` is dramatically cheaper than exact distinct at scale.",
    { added: /count\s*\(\s*distinct/i, pathGlob: /(marts|reporting)/i },
    { add: "count(distinct user_id)", path: "models/marts/m.sql" },
    { add: "count(user_id)", path: "models/marts/m.sql" },
  ),
  r(
    "bq-string-comparison-collation",
    "sql_correctness",
    "suggestion",
    "BigQuery: case-sensitive string join",
    "BigQuery string comparison is case-sensitive by default; normalize with LOWER or set collation.",
    { added: /\bon\s+\w+\.\w*(name|code|sku)\b\s*=\s*\w+\./i },
    { add: "on a.sku = b.sku" },
    { add: "on lower(a.sku) = lower(b.sku)" },
  ),
]

const SNOWFLAKE: Rule[] = [
  r(
    "sf-variant-no-cast",
    "sql_correctness",
    "suggestion",
    "Snowflake: VARIANT path used without explicit cast",
    "Reading `col:field` from a VARIANT returns VARIANT; cast (`::string`) so downstream types are stable.",
    { added: /\w+:[a-z_]\w*(?!\s*::)/i, unless: /::|http|case\s+when/i },
    { add: "select payload:user_id from t" },
    { add: "select payload:user_id::int from t" },
  ),
  r(
    "sf-flatten-explosion",
    "fanout",
    "suggestion",
    "Snowflake: LATERAL FLATTEN multiplies rows",
    "`LATERAL FLATTEN(input => arr)` produces one row per element; verify the fan-out is intended.",
    { added: /lateral\s+flatten\s*\(/i },
    { add: "from t, lateral flatten(input => t.items)" },
    { add: "from t" },
  ),
  r(
    "sf-time-travel",
    "sql_correctness",
    "warning",
    "Snowflake: time-travel (AT/BEFORE) in a model",
    "`AT(TIMESTAMP …)`/`BEFORE(STATEMENT …)` reads historical data — non-reproducible in a model.",
    { added: /\b(at|before)\s*\(\s*(timestamp|offset|statement)\s*=>/i },
    { add: "from t at(offset => -60)" },
    { add: "from t" },
  ),
  r(
    "sf-result-scan",
    "sql_correctness",
    "warning",
    "Snowflake: RESULT_SCAN in a model",
    "`RESULT_SCAN(LAST_QUERY_ID())` depends on session state and can't be reproduced by dbt.",
    { added: /result_scan\s*\(/i },
    { add: "from table(result_scan(last_query_id()))" },
    { add: "from {{ ref('x') }}" },
  ),
  r(
    "sf-zeroifnull-nonportable",
    "sql_quality",
    "suggestion",
    "Snowflake-specific ZEROIFNULL/IFF",
    "`ZEROIFNULL`/`IFF`/`DECODE` are Snowflake-only; use COALESCE/CASE for portability.",
    { added: /\b(zeroifnull|iff|decode|nvl2)\s*\(/i },
    { add: "zeroifnull(x)" },
    { add: "coalesce(x, 0)" },
  ),
  r(
    "sf-array-agg-no-order",
    "sql_correctness",
    "suggestion",
    "Snowflake: ARRAY_AGG without WITHIN GROUP order",
    "`ARRAY_AGG` without `WITHIN GROUP (ORDER BY …)` builds the array in non-deterministic order.",
    { added: /array_agg\s*\(/i, unless: /within\s+group/i },
    { add: "array_agg(id)" },
    { add: "array_agg(id) within group (order by id)" },
  ),
  r(
    "sf-transient-loss",
    "materialization",
    "suggestion",
    "Snowflake: transient table has no fail-safe",
    "A `transient` materialization saves storage but loses Fail-safe recovery; confirm that's acceptable.",
    { added: /transient\s*[=:]\s*true|materialized\s*[=:]\s*['"]?transient/i },
    { add: "{{ config(transient=true) }}" },
    { add: "{{ config(materialized='table') }}" },
  ),
  r(
    "sf-copy-into",
    "sql_correctness",
    "critical",
    "Snowflake: COPY INTO / PUT inside a model",
    "`COPY INTO`/`PUT`/`GET` are loading commands, not transforms — they don't belong in a model.",
    { added: /\b(copy\s+into|put\s+file|get\s+@)\b/i },
    { add: "copy into t from @stage" },
    { add: "select * from t" },
  ),
  r(
    "sf-ilike-perf",
    "warehouse_cost",
    "suggestion",
    "Snowflake: ILIKE is case-insensitive scan",
    "`ILIKE` can't use search-optimization the way an anchored equality can; prefer LOWER(col)=… where possible.",
    { added: /\bilike\b/i },
    { add: "where name ilike '%shirt%'" },
    { add: "where lower(name) = 'shirt'" },
  ),
  r(
    "sf-getdate-nonportable",
    "sql_quality",
    "suggestion",
    "Snowflake/SQL Server GETDATE() is non-portable",
    "`GETDATE()`/`SYSDATE` aren't standard; use `current_timestamp` (and avoid clocks in transforms).",
    { added: /\b(getdate|sysdate)\s*\(/i },
    { add: "select getdate()" },
    { add: "select current_timestamp() as _loaded_at" },
  ),
  r(
    "sf-sample-clause",
    "sql_correctness",
    "warning",
    "Snowflake: SAMPLE/TABLESAMPLE returns random subset",
    "`SAMPLE (n)` returns a different random subset each run — non-deterministic and lossy in a model.",
    { added: /\bsample\s*\(\s*\d/i },
    { add: "from t sample (10)" },
    { add: "from t" },
  ),
]

const REDSHIFT: Rule[] = [
  r(
    "rs-no-distkey-sortkey",
    "warehouse_cost",
    "suggestion",
    "Redshift: large table without dist/sort keys",
    "A Redshift `table` over a big source with no `dist`/`sort` config redistributes on every join — slow.",
    {
      newSql: /materialized\s*[=:]\s*['"]?table/i,
      absentNewSql: /(dist\s*[=:]|sort\s*[=:]|diststyle|sortkey)/i,
      pathGlob: /(marts|fct_|fact_)/i,
    },
    {
      add: "{{ config(materialized='table') }} select 1 from fct",
      newSql: "{{ config(materialized='table') }} select 1 from fct",
      path: "models/marts/fct_x.sql",
    },
    {
      add: "{{ config(materialized='table', sort='id') }} select 1",
      newSql: "{{ config(materialized='table', sort='id') }} select 1",
      path: "models/marts/fct_x.sql",
    },
  ),
  r(
    "rs-varchar-default",
    "contract_violation",
    "suggestion",
    "Redshift: VARCHAR without length defaults to 256",
    "Redshift `VARCHAR` defaults to 256 chars and truncates silently; size it explicitly for long text.",
    { added: /cast\s*\(\s*\w+\s+as\s+varchar\s*\)/i },
    { add: "cast(notes as varchar)" },
    { add: "cast(notes as varchar(4096))" },
  ),
  r(
    "rs-listagg-limit",
    "sql_correctness",
    "suggestion",
    "Redshift: LISTAGG overflows past 64KB",
    "Redshift `LISTAGG` errors when the result exceeds 64KB; bound or pre-truncate the inputs.",
    { added: /\blistagg\s*\(/i },
    { add: "listagg(comment, ',')" },
    { add: "array_agg(comment)" },
  ),
  r(
    "rs-leader-node-fn",
    "sql_correctness",
    "warning",
    "Redshift: leader-node-only function on a table",
    "`GENERATE_SERIES`/some functions run only on the leader node and error when used with table data.",
    { added: /\bgenerate_series\s*\(/i },
    { add: "select generate_series(1, n) from t" },
    { add: "from {{ ref('numbers') }}" },
  ),
  r(
    "rs-getdate",
    "idempotency",
    "suggestion",
    "Redshift: GETDATE()/SYSDATE in transform",
    "`GETDATE()`/`SYSDATE` bake run time into output (non-idempotent); pass an as-of var.",
    { added: /\b(getdate|sysdate)\b/i },
    { add: "where d > getdate() - 7" },
    { add: "where d > '2024-01-01'" },
  ),
  r(
    "rs-super-no-cast",
    "sql_correctness",
    "suggestion",
    "Redshift: SUPER path without cast",
    "Reading from a SUPER column without casting yields SUPER; cast for stable downstream types.",
    { added: /\w+\.\w+\s*::\s*super\b|\bjson_extract_path_text\s*\(/i },
    { add: "select json_extract_path_text(data, 'id')" },
    { add: "select id from t" },
  ),
]

const DATABRICKS: Rule[] = [
  r(
    "dbx-explode-fanout",
    "fanout",
    "suggestion",
    "Spark/Databricks: explode() multiplies rows",
    "`explode(array)`/`posexplode` emits one row per element — a fan-out; verify downstream grain.",
    { added: /\b(explode|posexplode|explode_outer)\s*\(/i },
    { add: "select explode(items)" },
    { add: "select items" },
  ),
  r(
    "dbx-collect-list-no-sort",
    "sql_correctness",
    "suggestion",
    "Spark: collect_list/collect_set ordering is non-deterministic",
    "`collect_list`/`collect_set` produce arrays in arbitrary order; sort explicitly if order matters.",
    { added: /\bcollect_(list|set)\s*\(/i, unless: /sort_array/i },
    { add: "collect_list(id)" },
    { add: "sort_array(collect_list(id))" },
  ),
  r(
    "dbx-merge-no-condition",
    "join_risk",
    "warning",
    "Databricks: MERGE INTO without a selective condition",
    "A `MERGE` whose `ON` is too broad (or `1=1`) rewrites the whole Delta table each run.",
    { added: /merge\s+into[\s\S]*\bon\s+(1\s*=\s*1|true)\b/i },
    { add: "merge into t using s on 1=1" },
    { add: "merge into t using s on t.id=s.id" },
  ),
  r(
    "dbx-no-partition-large",
    "warehouse_cost",
    "suggestion",
    "Databricks: large Delta table without partitioning/Z-ORDER",
    "A big Delta `table` with no `partition_by`/Z-ORDER scans all files; add partitioning for prune-ability.",
    {
      newSql: /materialized\s*[=:]\s*['"]?(table|incremental)/i,
      absentNewSql: /(partition_by|zorder|z_order|liquid)/i,
      pathGlob: /(marts|fct_|fact_)/i,
    },
    {
      add: "{{ config(materialized='table') }} select 1 from fct",
      newSql: "{{ config(materialized='table') }} select 1 from fct",
      path: "models/marts/fct_x.sql",
    },
    {
      add: "{{ config(materialized='table', partition_by=['d']) }} select 1",
      newSql: "{{ config(materialized='table', partition_by=['d']) }} select 1",
      path: "models/marts/fct_x.sql",
    },
  ),
  r(
    "dbx-cache-in-model",
    "sql_quality",
    "suggestion",
    "Spark: CACHE/UNCACHE TABLE in a model",
    "`CACHE TABLE`/`REFRESH` are session/runtime ops, not transforms — remove from model SQL.",
    { added: /\b(cache\s+table|uncache\s+table|refresh\s+table)\b/i },
    { add: "cache table t" },
    { add: "select * from t" },
  ),
  r(
    "dbx-string-to-date-fmt",
    "sql_correctness",
    "suggestion",
    "Spark: to_date/to_timestamp without format",
    "`to_date(str)` without an explicit format guesses and silently NULLs unparseable values.",
    { added: /\bto_(date|timestamp)\s*\(\s*[a-z_][\w.]*\s*\)/i },
    { add: "to_date(order_date)" },
    { add: "to_date(order_date, 'yyyy-MM-dd')" },
  ),
]

const STYLE: Rule[] = [
  r(
    "where-1-eq-1",
    "sql_quality",
    "suggestion",
    "no-op WHERE 1=1 / WHERE true",
    "`where 1=1`/`where true` is a no-op (often a leftover scaffold); remove or add the real predicate.",
    { added: /\bwhere\s+(1\s*=\s*1|true)\b/i },
    { add: "where 1=1" },
    { add: "where status = 'x'" },
  ),
  r(
    "trailing-semicolon",
    "sql_quality",
    "suggestion",
    "trailing semicolon in a model",
    "dbt models shouldn't end in `;` — it can break wrapping/CTAS on some adapters.",
    { added: /;\s*$/ },
    { add: "select 1;" },
    { add: "select 1" },
  ),
  r(
    "multiple-statements",
    "sql_correctness",
    "critical",
    "multiple statements in one model",
    "A model must be a single statement; two `;`-separated statements won't materialize correctly.",
    { added: /;\s*\S+[\s\S]*;/ },
    { add: "select 1; select 2;" },
    { add: "select 1" },
  ),
  r(
    "implicit-alias-no-as",
    "sql_quality",
    "suggestion",
    "column alias without AS",
    "Aliasing as `col x` (no `AS`) is ambiguous and easy to misread as a missing comma.",
    { added: /select\s+\w+\s+\w+\s*,/i, unless: /\bas\b|distinct|\*/i },
    { add: "select amount total," },
    { add: "select amount as total," },
  ),
  r(
    "generic-cte-name",
    "sql_quality",
    "suggestion",
    "non-descriptive CTE name",
    "CTE names like `tmp`/`t1`/`cte`/`final2` hide intent; name them for what they compute.",
    { added: /\bwith\s+(tmp|temp|t1|t2|cte|x|foo|test|final2)\s+as\b/i },
    { add: "with tmp as (select 1)" },
    { add: "with daily_revenue as (select 1)" },
  ),
  r(
    "nested-case",
    "sql_quality",
    "suggestion",
    "deeply nested CASE expression",
    "Nested `CASE WHEN … CASE WHEN` is hard to verify; flatten with combined conditions or a mapping.",
    { newSql: /case\s+when[\s\S]*\bcase\s+when/i },
    { add: "case when a then case when b then 1 end end" },
    { add: "case when a then 1 end" },
  ),
  r(
    "hardcoded-env-name",
    "sql_quality",
    "warning",
    "hardcoded environment/schema name",
    "A literal `'prod'`/`'production'`/`analytics.` in SQL breaks across environments; use target/var.",
    { added: /['"](prod|production|staging|dev)['"]/i },
    { add: "where env = 'production'" },
    { add: "where env = '{{ target.name }}'" },
  ),
  r(
    "like-no-wildcard",
    "sql_quality",
    "suggestion",
    "LIKE without a wildcard — use =",
    "`like 'exact'` with no `%`/`_` is just equality; `=` is clearer and faster.",
    { added: /\blike\s+'[^%_']+'/i },
    { add: "where code like 'ABC'" },
    { add: "where code like 'ABC%'" },
  ),
  r(
    "recursive-cte",
    "sql_quality",
    "suggestion",
    "recursive CTE — verify termination",
    "`WITH RECURSIVE` can loop infinitely or blow up; confirm a base case and depth bound.",
    { added: /\bwith\s+recursive\b/i },
    { add: "with recursive r as (select 1)" },
    { add: "with r as (select 1)" },
  ),
  r(
    "pivot-portability",
    "sql_quality",
    "suggestion",
    "PIVOT/UNPIVOT is dialect-specific",
    "`PIVOT`/`UNPIVOT` syntax varies by warehouse and is hard to test; consider conditional aggregation.",
    { added: /\b(pivot|unpivot)\s*\(/i },
    { add: "from t pivot(sum(x) for k in ('a'))" },
    { add: "sum(case when k='a' then x end)" },
  ),
  r(
    "top-n-no-order",
    "sql_correctness",
    "suggestion",
    "TOP n without ORDER BY",
    "`SELECT TOP n` without `ORDER BY` returns arbitrary rows; add an explicit order.",
    { added: /select\s+top\s+\d+/i, unless: /order\s+by/i },
    { add: "select top 10 * from t" },
    { add: "select top 10 * from t order by d" },
  ),
  r(
    "group-by-alias",
    "sql_quality",
    "suggestion",
    "GROUP BY on a SELECT alias",
    "Grouping by a select-list alias isn't portable (errors on some warehouses); repeat the expression.",
    { added: /\bgroup\s+by\s+\w+_(amt|amount|total|cnt|count)\b/i },
    { add: "group by total_amount" },
    { add: "group by customer_id" },
  ),
  r(
    "interval-string-literal",
    "sql_quality",
    "suggestion",
    "string interval literal portability",
    "`interval '1 day'` literal syntax differs across warehouses; prefer dateadd/date_add functions.",
    { added: /interval\s+'\d+\s*\w+'/i },
    { add: "d + interval '1 day'" },
    { add: "dateadd(day, 1, d)" },
  ),
  r(
    "date-plus-int",
    "sql_correctness",
    "suggestion",
    "integer arithmetic on a date",
    "`date + 7` (bare int) isn't portable and is ambiguous (days? seconds?); use dateadd/interval.",
    { added: /\b\w*(date|_at|_dt)\b\s*[+\-]\s*\d+\b/i },
    { add: "select order_date + 7" },
    { add: "select dateadd(day, 7, order_date)" },
  ),
]

const MISC: Rule[] = [
  r(
    "order-by-rand",
    "idempotency",
    "warning",
    "ORDER BY RANDOM() is non-deterministic + costly",
    "Ordering by a random value gives different output each run and forces a full sort.",
    { added: /order\s+by\s+(rand|random)\s*\(/i },
    { add: "order by random()" },
    { add: "order by created_at" },
  ),
  r(
    "limit-no-order",
    "sql_correctness",
    "suggestion",
    "LIMIT without ORDER BY returns arbitrary rows",
    "`LIMIT n` with no `ORDER BY` picks non-deterministic rows that vary run-to-run.",
    { newSql: /\blimit\s+\d+/i, absentNewSql: /order\s+by/i },
    { add: "select a from t limit 10", newSql: "select a from t limit 10" },
    { add: "select a from t order by a limit 10", newSql: "select a from t order by a limit 10" },
  ),
  r(
    "nullif-self",
    "sql_correctness",
    "warning",
    "NULLIF(x, x) is always NULL",
    "`nullif(x, x)` always returns NULL — almost certainly a typo.",
    { added: /nullif\s*\(\s*(\w[\w.]*)\s*,\s*\1\s*\)/i },
    { add: "nullif(amount, amount)" },
    { add: "nullif(amount, 0)" },
  ),
  r(
    "coalesce-single-arg",
    "sql_quality",
    "suggestion",
    "COALESCE with one argument is a no-op",
    "`coalesce(x)` does nothing; remove it or add the fallback value.",
    { added: /coalesce\s*\(\s*[\w.]+\s*\)/i },
    { add: "coalesce(amount)" },
    { add: "coalesce(amount, 0)" },
  ),
  r(
    "uncorrelated-exists",
    "sql_correctness",
    "warning",
    "EXISTS subquery not correlated",
    "`exists (select 1 from t)` with no link to the outer query is constant (all-or-nothing).",
    { added: /\bexists\s*\(\s*select\b[^)]*\bfrom\b[^)]*\)/i, unless: /where[\s\S]*\b\w+\.\w+\s*=\s*\w+\./i },
    { add: "where exists (select 1 from orders)" },
    { add: "where exists (select 1 from orders o where o.cid = c.id)" },
  ),
  r(
    "in-with-null",
    "sql_correctness",
    "suggestion",
    "NULL inside an IN-list",
    "A `NULL` in an IN-list never matches and is dead; in a NOT IN it empties the result.",
    { added: /\bin\s*\([^)]*\bnull\b[^)]*\)/i },
    { add: "where x in (1, null, 3)" },
    { add: "where x in (1, 2, 3)" },
  ),
  r(
    "integer-division",
    "sql_correctness",
    "suggestion",
    "integer division truncates",
    "`5 / 2` does integer division (=2) on many warehouses; cast a side to numeric for a real ratio.",
    { added: /(?<![\d.])\d+\s*\/\s*\d+(?![\d.])/ },
    { add: "select 7 / 2 as r" },
    { add: "select 7.0 / 2 as r" },
  ),
  r(
    "mod-by-zero",
    "sql_correctness",
    "warning",
    "modulo / division by a literal zero",
    "`mod(x, 0)` / `x % 0` errors at runtime.",
    { added: /(mod\s*\(\s*[^,]+,\s*0\s*\)|%\s*0\b)/i },
    { add: "select mod(x, 0)" },
    { add: "select mod(x, 7)" },
  ),
  r(
    "not-equal-drops-null",
    "sql_correctness",
    "suggestion",
    "<>/!= silently excludes NULL rows",
    "`col <> 'x'` drops rows where col IS NULL; add `or col is null` if those should remain.",
    { added: /\b[\w.]+\s*(<>|!=)\s*'/i },
    { add: "where status <> 'cancelled'" },
    { add: "where status is distinct from 'cancelled'" },
  ),
  r(
    "boolean-eq-literal",
    "sql_quality",
    "suggestion",
    "comparing boolean to true/'true'",
    "`is_active = true` is redundant; use the boolean directly. `= 'true'` (string) is a type bug.",
    { added: /\b\w+\s*=\s*('true'|'false')/i },
    { add: "where active = 'true'" },
    { add: "where active" },
  ),
  r(
    "redundant-subquery",
    "sql_quality",
    "suggestion",
    "redundant wrapping subquery",
    "`from (select * from t)` adds a pointless nesting level; select from the table directly.",
    { added: /from\s*\(\s*select\s+\*\s+from\s+[\w.]+\s*\)/i },
    { add: "from (select * from raw_orders)" },
    { add: "from {{ ref('t') }}" },
  ),
  r(
    "distinct-on",
    "sql_quality",
    "suggestion",
    "DISTINCT ON is Postgres-specific",
    "`DISTINCT ON (…)` isn't portable; use `qualify row_number()` for first-row-per-group.",
    { added: /distinct\s+on\s*\(/i },
    { add: "select distinct on (id) * from t" },
    { add: "qualify row_number() over (partition by id order by d) = 1" },
  ),
  r(
    "fetch-first",
    "sql_quality",
    "suggestion",
    "FETCH FIRST portability",
    "`FETCH FIRST n ROWS` isn't supported everywhere; `LIMIT` (with ORDER BY) is more portable.",
    { added: /fetch\s+first\s+\d+/i },
    { add: "fetch first 10 rows only" },
    { add: "limit 10" },
  ),
  r(
    "string-truncate-left",
    "sql_correctness",
    "suggestion",
    "LEFT/SUBSTR truncation may cut data",
    "`left(x, n)`/`substr(x,1,n)` silently truncates longer values; confirm n covers real lengths.",
    { added: /\b(left|substr|substring)\s*\(\s*[\w.]+\s*,\s*\d/i },
    { add: "left(description, 50)" },
    { add: "description" },
  ),
  r(
    "concat-number-string",
    "sql_correctness",
    "suggestion",
    "implicit number→string in concat",
    "Concatenating a number with `||`/concat relies on an implicit cast; cast explicitly.",
    { added: /\b\d+\s*\|\|\s*'|'\s*\|\|\s*\d/i },
    { add: "select 5 || ' items'" },
    { add: "select cast(5 as string) || ' items'" },
  ),
  r(
    "redundant-distinct-count",
    "sql_quality",
    "suggestion",
    "COUNT(DISTINCT <constant>)",
    "`count(distinct 1)` is just `min(1)`/`sign(count(*))`; almost certainly a mistake.",
    { added: /count\s*\(\s*distinct\s+\d+\s*\)/i },
    { add: "count(distinct 1)" },
    { add: "count(distinct id)" },
  ),
  r(
    "in-empty-list",
    "sql_correctness",
    "warning",
    "empty IN () list",
    "`in ()` is invalid or always-false; likely a templating bug that emptied the list.",
    { added: /\bin\s*\(\s*\)/i },
    { add: "where id in ()" },
    { add: "where id in (1)" },
  ),
  r(
    "cast-chain",
    "sql_quality",
    "suggestion",
    "chained casts",
    "`cast(cast(x as string) as int)` round-trips types and hides intent; cast once.",
    { added: /cast\s*\(\s*cast\s*\(/i },
    { add: "cast(cast(x as string) as int)" },
    { add: "cast(x as int)" },
  ),
  r(
    "union-select-star",
    "sql_correctness",
    "warning",
    "SELECT * in a UNION",
    "`select *` on either side of a UNION breaks (column count/order) the moment a column is added.",
    { newSql: /select\s+\*[\s\S]*\bunion\b/i },
    { add: "select * from a union all select * from b" },
    { add: "select id from a union all select id from b" },
  ),
  r(
    "group-by-all-ordinal",
    "sql_quality",
    "suggestion",
    "GROUP BY ALL hides grain",
    "`GROUP BY ALL` is convenient but obscures the grain and silently changes when you add a column.",
    { added: /\bgroup\s+by\s+all\b/i },
    { add: "group by all" },
    { add: "group by customer_id, order_date" },
  ),
  r(
    "where-not-null-or",
    "sql_correctness",
    "suggestion",
    "OR with IS NULL can defeat an index/prune",
    "`where a = x or a is null` is hard to optimize; consider coalesce or a UNION.",
    { added: /\bwhere\b[\s\S]*=\s*[^;]*\bor\b[\s\S]*\bis\s+null\b/i },
    { add: "where status = 'x' or status is null" },
    { add: "where coalesce(status,'x') = 'x'" },
  ),
  r(
    "timestamp-string-format",
    "sql_correctness",
    "suggestion",
    "parsing date from string without format",
    "`to_date`/`parse_date` without an explicit format guesses and NULLs unparseable rows.",
    { added: /\b(to_date|to_timestamp|parse_date|parse_timestamp)\s*\(\s*[\w.]+\s*\)/i },
    { add: "to_date(order_date)" },
    { add: "to_date('%Y-%m-%d', order_date)" },
  ),
  r(
    "bool-and-or-mix-3",
    "sql_correctness",
    "suggestion",
    "three-way AND/OR mix needs parentheses",
    "Long `a and b or c and d` chains are precedence traps; parenthesize the intended grouping.",
    { added: /\b\w+[^;]*\band\b[^;]*\bor\b[^;]*\band\b/i, unless: /\(/ },
    { add: "where a and b or c and d" },
    { add: "where (a and b) or (c and d)" },
  ),
  r(
    "count-of-nullable-pct",
    "sql_correctness",
    "suggestion",
    "rate from COUNT(col) over COUNT(*)",
    "`count(col)/count(*)` mixes NULL-skipping and row counts — usually a denominator bug.",
    { added: /count\s*\(\s*[\w.]+\s*\)\s*\/\s*count\s*\(\s*\*\s*\)/i },
    { add: "count(converted)/count(*)" },
    { add: "countif(converted)/count(*)" },
  ),
  r(
    "hardcoded-row-id",
    "sql_quality",
    "suggestion",
    "hardcoded id literal in a predicate",
    "Filtering on a specific id (`where id = 12345`) is usually leftover debugging.",
    { added: /\bwhere\b[\s\S]*\b\w*id\s*=\s*\d{3,}/i },
    { add: "where customer_id = 12345" },
    { add: "where customer_id = c.id" },
  ),
  r(
    "select-now-column",
    "idempotency",
    "suggestion",
    "now() materialized as a column value",
    "Storing `current_timestamp` as a data column (not an audit field) bakes run time into the data.",
    { added: /\b(current_timestamp|now|current_date)\s*\(\s*\)\s+as\s+(?!_)/i },
    { add: "current_timestamp() as snapshot_time" },
    { add: "current_timestamp() as _loaded_at" },
  ),
  r(
    "string-in-numeric-agg",
    "sql_correctness",
    "suggestion",
    "SUM/AVG over a string-typed column",
    "Aggregating a column that looks string-typed (`_str`/`_code`) implies a missing cast.",
    { added: /\b(sum|avg)\s*\(\s*\w*(_str|_code|_text)\b/i },
    { add: "sum(amount_str)" },
    { add: "sum(cast(amount_str as numeric))" },
  ),
  r(
    "join-without-schema-prefix",
    "sql_quality",
    "suggestion",
    "join target not via ref()/source()",
    "A join to a bare table name (not `ref`/`source`) drops the lineage edge.",
    { added: /\bjoin\s+[a-z_]\w*\s+\w+\s+on\b/i, unless: /\{\{|unnest|lateral|flatten/i },
    { add: "join orders o on o.id = c.id" },
    { add: "join {{ ref('orders') }} o on o.id = c.id" },
  ),
  r(
    "subquery-in-select-count",
    "warehouse_cost",
    "suggestion",
    "correlated COUNT subquery in SELECT",
    "A `(select count(*) …)` per row is O(n²); rewrite as a GROUP BY join.",
    { added: /,\s*\(\s*select\s+count\s*\(/i },
    { add: "select id, (select count(*) from o where o.cid=c.id)" },
    { add: "select id, order_count from c" },
  ),
  r(
    "case-when-no-end",
    "sql_correctness",
    "warning",
    "CASE without END",
    "A `CASE WHEN` with no matching `END` on the line/expression is a syntax error.",
    { added: /\bcase\s+when\b[^;]*$/i, unless: /\bend\b|\{\{|\{%/i },
    { add: "case when x > 0 then 1" },
    { add: "case when x > 0 then 1 end" },
  ),
  r(
    "double-aggregation-alias",
    "sql_correctness",
    "suggestion",
    "aggregate of an aggregate alias",
    "Referencing an aggregate alias inside another aggregate needs a subquery/CTE, not the same SELECT.",
    { added: /\b(sum|avg|max|min)\s*\(\s*\w*(total|sum|count|avg)_/i },
    { add: "avg(total_revenue)" },
    { add: "avg(revenue)" },
  ),
  r(
    "where-cast-column",
    "warehouse_cost",
    "suggestion",
    "CAST on a filtered column blocks pruning",
    "Casting a column in WHERE (e.g. `cast(d as date) = …`) prevents partition/cluster pruning.",
    { added: /\bwhere\b[^;]*\bcast\s*\(/i },
    { add: "where cast(created_at as date) = '2024-01-01'" },
    { add: "where created_at >= '2024-01-01'" },
  ),
  r(
    "inequality-join",
    "warehouse_cost",
    "suggestion",
    "inequality / range join is expensive",
    "`join … on a.d between b.start and b.end` can't hash-join and may explode; bound it carefully.",
    { added: /\bon\b[^;]*\bbetween\b/i },
    { add: "on a.d between b.start and b.end" },
    { add: "on a.id = b.id" },
  ),
  r(
    "string-concat-key-no-sep",
    "dedup",
    "suggestion",
    "key built by concatenation without a separator",
    "`a || b` as a key collides (`'1'||'23'` == `'12'||'3'`); add a delimiter or use generate_surrogate_key.",
    { added: /\b\w+\s*\|\|\s*\w+\s+as\s+\w*(key|id|sk)\b/i },
    { add: "a || b as customer_key" },
    { add: "a || '-' || b as customer_key" },
  ),
  r(
    "count-star-with-left-join",
    "fanout",
    "suggestion",
    "COUNT(*) after a LEFT JOIN counts unmatched rows",
    "`count(*)` after a LEFT JOIN counts the 1 NULL-filled row for non-matches; use count(child.key).",
    { newSql: /count\s*\(\s*\*\s*\)[\s\S]*left\s+join/i },
    { add: "select a.id, count(*) from a left join b on a.id=b.aid group by 1" },
    { add: "select a.id, count(b.id) from a left join b on a.id=b.aid group by 1" },
  ),
  r(
    "string-length-no-trim",
    "sql_correctness",
    "suggestion",
    "length() on un-trimmed string",
    "`length(x) = 0` misses whitespace-only values; trim first or check for blanks explicitly.",
    { added: /\blength\s*\(\s*[\w.]+\s*\)\s*=\s*0/i },
    { add: "where length(name) = 0" },
    { add: "where trim(name) = ''" },
  ),
  r(
    "update-from-in-model",
    "sql_correctness",
    "critical",
    "UPDATE … FROM in a model",
    "An `UPDATE` statement mutates data directly, bypassing dbt's rebuild model — not allowed in a model.",
    { added: /\bupdate\s+\w+\s+set\b/i },
    { add: "update t set x = 1" },
    { add: "select 1 as x" },
  ),
  r(
    "truncate-in-model",
    "sql_correctness",
    "critical",
    "TRUNCATE inside a model",
    "`TRUNCATE` empties a table on every build — destructive and not a transform.",
    { added: /\btruncate\s+(table\s+)?\w/i },
    { add: "truncate table staging" },
    { add: "select * from staging" },
  ),
  r(
    "ddl-grant",
    "pii_exposure",
    "warning",
    "GRANT/REVOKE statement in a model",
    "Access-control DDL (`GRANT`/`REVOKE`) doesn't belong in transform SQL; manage grants via config/hooks.",
    { added: /\b(grant|revoke)\s+\w/i },
    { add: "grant select on t to role analyst" },
    { add: "select 1" },
  ),
  r(
    "create-or-replace",
    "sql_correctness",
    "critical",
    "CREATE OR REPLACE in a model",
    "dbt issues the CREATE; a hand-written `CREATE OR REPLACE` conflicts with materialization.",
    { added: /\bcreate\s+or\s+replace\b/i },
    { add: "create or replace table t as select 1" },
    { add: "select 1" },
  ),
  r(
    "group-by-count-mismatch",
    "sql_quality",
    "suggestion",
    "many GROUP BY positions — verify against SELECT",
    "Long positional `group by 1,2,3,4,5` is fragile; one reorder silently changes the grain.",
    { added: /\bgroup\s+by\s+\d+(\s*,\s*\d+){3,}/i },
    { add: "group by 1,2,3,4,5" },
    { add: "group by customer_id" },
  ),
  r(
    "ilike-anywhere",
    "warehouse_cost",
    "suggestion",
    "ILIKE with surrounding wildcards",
    "`ilike '%x%'` is a case-insensitive full scan; consider a search index or normalized column.",
    { added: /\bilike\s+'%[^']*%'/i },
    { add: "where name ilike '%shirt%'" },
    { add: "where name = 'shirt'" },
  ),
]

const MISC2: Rule[] = [
  r(
    "coalesce-all-null",
    "sql_correctness",
    "warning",
    "COALESCE(NULL, NULL) is always NULL",
    "Every COALESCE branch is a NULL literal — the expression can only be NULL.",
    { added: /coalesce\s*\(\s*null\s*,\s*null/i },
    { add: "coalesce(null, null)" },
    { add: "coalesce(a, 0)" },
  ),
  r(
    "self-equality",
    "sql_correctness",
    "warning",
    "predicate compares a column to itself",
    "`where x = x` is true for non-NULL rows and silently drops NULLs — almost always a typo.",
    { added: /\bwhere\s+(\w[\w.]*)\s*=\s*\1\b/i },
    { add: "where status = status" },
    { add: "where status = active" },
  ),
  r(
    "join-self-column",
    "join_risk",
    "warning",
    "join condition compares a column to itself",
    "`on a.x = a.x` doesn't relate the tables (cartesian on that key). Reference both sides.",
    { added: /\bon\s+(\w+\.\w+)\s*=\s*\1\b/i },
    { add: "on a.id = a.id" },
    { add: "on a.id = b.id" },
  ),
  r(
    "count-distinct-star",
    "sql_correctness",
    "warning",
    "COUNT(DISTINCT *) is invalid/ambiguous",
    "`count(distinct *)` isn't valid SQL on most warehouses; count distinct explicit columns.",
    { added: /count\s*\(\s*distinct\s*\*/i },
    { add: "count(distinct *)" },
    { add: "count(distinct id)" },
  ),
  r(
    "empty-string-eq",
    "sql_correctness",
    "suggestion",
    "comparing to empty string '' ",
    "`= ''` treats empty and NULL differently across warehouses; decide and handle both explicitly.",
    { added: /=\s*''/ },
    { add: "where name = ''" },
    { add: "where name is null" },
  ),
  r(
    "decimal-no-scale",
    "sql_correctness",
    "suggestion",
    "money cast to NUMERIC without scale",
    "`cast(amount as numeric)` (no precision/scale) may default to integer rounding on some engines.",
    { added: /cast\s*\(\s*\w*(amount|price|revenue|total|cost)\w*\s+as\s+(numeric|decimal)\s*\)/i },
    { add: "cast(amount as numeric)" },
    { add: "cast(amount as numeric(38,4))" },
  ),
  r(
    "substr-zero-index",
    "sql_correctness",
    "suggestion",
    "SUBSTR starting at position 0",
    "SQL string positions are 1-based; `substr(x, 0, n)` behaves inconsistently across warehouses.",
    { added: /\bsubstr(ing)?\s*\(\s*[\w.]+\s*,\s*0\b/i },
    { add: "substr(code, 0, 3)" },
    { add: "substr(code, 1, 3)" },
  ),
  r(
    "current-user",
    "idempotency",
    "suggestion",
    "CURRENT_USER/SESSION_USER in a model",
    "Session identity functions vary by who runs the build, making output non-reproducible.",
    { added: /\b(current_user|session_user|current_role)\b/i },
    { add: "select current_user as u" },
    { add: "select '{{ target.name }}' as env" },
  ),
  r(
    "greatest-least-null",
    "sql_correctness",
    "suggestion",
    "GREATEST/LEAST NULL behavior varies",
    "Some warehouses return NULL if any GREATEST/LEAST argument is NULL — guard nullable inputs.",
    { added: /\b(greatest|least)\s*\(/i, unless: /coalesce|nvl|ifnull/i },
    { add: "greatest(a, b)" },
    { add: "greatest(coalesce(a,0), coalesce(b,0))" },
  ),
  r(
    "json-extract-no-cast",
    "sql_correctness",
    "suggestion",
    "JSON extraction without a cast",
    "`json_extract`/`json_value` returns JSON/string; cast so downstream types are stable.",
    { added: /json_(extract|value|query)\s*\(/i, unless: /::|cast/i },
    { add: "json_extract(payload, '$.id')" },
    { add: "cast(json_extract(payload, '$.id') as int)" },
  ),
  r(
    "where-leading-and",
    "sql_correctness",
    "warning",
    "WHERE immediately followed by AND/OR",
    "`where and …` is a syntax error — usually a templating bug that dropped the first predicate.",
    { added: /\bwhere\s+(and|or)\b/i },
    { add: "where and status = 'x'" },
    { add: "where status = 'x'" },
  ),
  r(
    "nested-coalesce",
    "sql_quality",
    "suggestion",
    "nested COALESCE",
    "`coalesce(coalesce(a,b),c)` flattens to `coalesce(a,b,c)`; simplify.",
    { added: /coalesce\s*\(\s*coalesce\s*\(/i },
    { add: "coalesce(coalesce(a,b),c)" },
    { add: "coalesce(a,b,c)" },
  ),
  r(
    "cast-as-text",
    "sql_quality",
    "suggestion",
    "non-portable type name (TEXT)",
    "`cast(x as text)` isn't supported on all warehouses; use `string`/`varchar`.",
    { added: /\bas\s+text\b/i },
    { add: "cast(x as text)" },
    { add: "cast(x as string)" },
  ),
  r(
    "order-desc-no-nulls",
    "sql_correctness",
    "suggestion",
    "ORDER BY DESC without NULLS ordering",
    "NULL position in `ORDER BY … DESC` differs across warehouses; specify `NULLS LAST/FIRST` for determinism.",
    { added: /order\s+by\s+[\w.]+\s+desc\b/i, unless: /nulls\s+(first|last)/i },
    { add: "order by updated_at desc" },
    { add: "order by updated_at desc nulls last" },
  ),
  r(
    "power-caret",
    "sql_correctness",
    "suggestion",
    "`^` is XOR, not power, on some warehouses",
    "`a ^ b` is bitwise XOR in BigQuery/Snowflake (power in Postgres); use POW()/POWER() for exponent.",
    { added: /[\w.)]\s*\^\s*\d/ },
    { add: "select value ^ 2" },
    { add: "select power(value, 2)" },
  ),
  r(
    "approx-in-financial",
    "sql_correctness",
    "suggestion",
    "approximate function in a financial model",
    "`APPROX_*`/`HLL` trade accuracy for speed — never use them where exact counts/sums are required.",
    {
      added: /\b(approx_count_distinct|approx_quantiles|hll_count)\b/i,
      pathGlob: /(revenue|finance|billing|fct_revenue)/i,
    },
    { add: "approx_count_distinct(id)", path: "models/marts/fct_revenue.sql" },
    { add: "count(distinct id)", path: "models/marts/fct_revenue.sql" },
  ),
]

CATALOG.push(
  ...CORRECTNESS,
  ...NULLS,
  ...DATETIME,
  ...TYPES,
  ...JOINS,
  ...AGG,
  ...WINDOWS,
  ...PERF,
  ...MATERIALIZATION,
  ...DBT_CONV,
  ...TESTS_CONTRACTS,
  ...SNAPSHOTS,
  ...SECURITY_PII,
  ...BIGQUERY,
  ...SNOWFLAKE,
  ...REDSHIFT,
  ...DATABRICKS,
  ...STYLE,
  ...MISC,
  ...MISC2,
  ...GENERATED,
)
